# Generated by Django 4.0 on 2022-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
