# Generated by Django 4.0 on 2022-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
