# Generated by Django 4.0 on 2022-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEMSapp', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
