# Generated by Django 4.0 on 2022-02-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEMSapp', '0004_alter_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
