# Generated by Django 4.0 on 2022-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEMSapp', '0006_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
