# Generated by Django 4.0 on 2022-03-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEMSapp', '0007_forms_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
