# Generated by Django 4.0 on 2022-03-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_add',
        ),
    ]
