# Generated by Django 4.0 on 2022-03-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_add',
            name='mobile',
            field=models.IntegerField(max_length=50),
        ),
    ]
