# Generated by Django 4.0 on 2022-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0004_alter_employee_add_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_add',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
