# Generated by Django 4.0 on 2022-03-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0005_alter_employee_add_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_add',
        ),
    ]
