# Generated by Django 4.0 on 2022-03-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentapp', '0006_delete_employee_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
