# Generated by Django 4.0 on 2022-04-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('basic_pay', models.IntegerField()),
                ('HRA', models.IntegerField()),
                ('TA', models.IntegerField()),
                ('DA', models.IntegerField()),
                ('IT', models.IntegerField()),
                ('PF', models.IntegerField()),
                ('Gross_salary', models.IntegerField()),
                ('Net_salary', models.IntegerField()),
            ],
        ),
    ]
